language: java

jdk:
  - openjdk11

addons:
  sonarcloud:
    organization: exasol
    token:
      secure: "fm3ZgsBgrTmDtL27WNdZ2dy3jZzxEVpPSEzJgeYpvM6i0zbLIcUJUew9KnWq6JXUTT6f6T5nKCcnd3+Lr0w/T9+cZ9FvZk3jf8ruJF9O9j9ap/xSkJnW+MzYl+r2jXeOzQ2VyIs6nZ+w8tqSiYznv9qCWjsWw38Do1M7dtGnKlk2jHZmajCWVc9duIWW7Ltp7mDj/ZZXvJ6WxySvnuiHxjP+LlrwLYCZ/7j3n44sky9Isads4e/5KY8NhLsexAY34pvG5up19FSsYQ+fb1yRbOkCL2U/88+tJMgG4cnzev800cZuclwipWZ0ZvMQiw6g2YLuS5N+d8YAscO3pV/cUGOp2NYQdvyx/zSoW4HZgSpnD+QuxC3OrDOEBNbdt0cO4I5Um60YQ83zVJh0r8EeWl7Mx8DJ2gz8wUQx49PdLx8Ar3jQeKtCIt7S1R/xu22wQNybpP5AKQcElGSnwIdLJ3/jnuACbRYz8YwpioChziz5ewsnq1fkKrBvy56Kcw49GuDqqOFxzamVlxhi77IdJ3lVW8YZL7vfDKMa4JH8BPFrazxV/y/LV+MTtT72FsaoP4Z/aiC/Lmz1GX+n70FKoXr7tWSQ7eo3yWI8VJnh+RU5ki6ysGvNMxKTY1wjoeDEYXNYjnVobYL6UNupBg+NFPttuc6xQGW2LcYx6bMDNco="

install:
  - travis_retry mvn dependency:resolve

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar

cache:
  directories:
    - "$HOME/.m2"